### ISSUE TITLE
Error installing dq3d windows

### ISSUE THREAD

**Issue by sarbabi** [neka-nat/dq3d#3]
Hi, I'm trying to install dq3d and get this error, attached in the screen shot.
the transformations in already installed.
Best Regards
![dq3d-installation_issue](https://user-images.githubusercontent.com/21973354/59105921-5d1d8b00-8935-11e9-8cd7-3a193f74ddc9.PNG)

**Comment by neka-nat** [comment]
Hi,
Thank you for the reporting.
I think that it is similar to the following error.
https://stackoverflow.com/questions/38290169/cannot-find-corecrt-h-universalcrt-includepath-is-wrong
